name: First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/checkout.yml
